version: "3.3"

services:
    fb-evenem-postgres:
        image: fb-evenem-postgres
        #image: marinoborges/fb-evenem-postgres
        ports:
            - "5432:5432"
        volumes:
            - fb-evenem-postgres-etc:/etc/postgresql
            - fb-evenem-postgres-log:/var/log/postgresql
            - fb-evenem-postgres-lib:/var/lib/postgresql
        deploy:
            replicas: 1

volumes:
    fb-evenem-postgres-etc:
        driver_opts:
            type: none
            o: bind
            device: "/docker-vol/fb-evenem-postgres/etc"
    fb-evenem-postgres-log:
        driver_opts:
            type: none
            o: bind
            device: "/docker-vol/fb-evenem-postgres/log"
    fb-evenem-postgres-lib:
        driver_opts:
            type: none
            o: bind
            device: "/docker-vol/fb-evenem-postgres/lib"
