version: "3.3"

services:
    traefik:
        image: traefik:1.7
        command:
            - "--docker"
            - "--docker.swarmmode"
            - "--docker.watch"
            - "--web"
            - "--loglevel=DEBUG"
        ports:
            - "80:80"
            - "8010:8080"
        networks:
            - traefik-net
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock"
        deploy:
            mode: global
            placement:
                constraints: [node.role == manager]
            restart_policy:
                condition: on-failure
            
    fb-evenem-wildfly:
        image: fb-evenem-wildfly
        #image: marinoborges/fb-evenem-wildfly
        ports:
            - "8080:8080"
        extra_hosts:
            #- "fb-evenem-postgresql.host:172.30.0.7"
            - "docker1:172.30.1.84"
            - "docker2:172.30.0.83"
            - "docker3:172.30.0.7"
        deploy:
            replicas: 2
            resources:
                reservations:
                    memory: 2100M
            labels:
                - "traefik.docker.network=fb-evenem-web_traefik-net"
                - "traefik.port=8080"
                - "traefik.frontend.rule=PathPrefix:/enem"
                - "traefik.backend.loadbalancer.stickiness=true"
        networks:
            - traefik-net
            
networks:
    traefik-net:
        driver: "overlay"
